name: Feature Story
description: Use this template to describe a new feature for the project.
title: "[Feature]: "
labels:
  - implementation
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Overview
        _Provide a high-level summary of the feature._

  - type: textarea
    id: user-story
    attributes:
      label: "User Story"
      description: "Briefly describe the feature from a user’s perspective."
      placeholder: "The [user] will use this feature to achieve [goal]."
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any extra details that might help developers understand the scope."
    validations:
      required: true
      
  - type: checkboxes
    id: general-acceptance-criteria
    attributes:
      label: "General Acceptance Criteria"
      description: "These must be met for any feature."
      options:
        - label: "Code follows the DRY (Don't Repeat Yourself) principle"
        - label: "Applicable components are reusable across the project"
        - label: "Each class and function includes proper JSDoc (`/** */`) documentation"
        - label: "All edge cases have been tested using Jasmine unit tests"
        - label: "Cypress E2E tests cover every scenario in the app"

  - type: textarea
    id: mockups
    attributes:
      label: "Mockups or References"
      description: "Attach relevant designs, Figma links, or references."
      placeholder: "Paste Figma or other design links here."
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: "Technical Notes"
      description: "List any technical constraints, dependencies, or additional details."
      placeholder: "This feature requires a backend API update."
    validations:
      required: false
      
  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "List any other features, stories, or tasks that this feature depends on."
      placeholder: "Feature A must be completed before this story."
    validations:
      required: false

